name: dart_devtools
description: DDC debugging tool based on Chrome DevTools
version: 0.0.1
homepage: https://github.com/dart-lang/devtools-frontend
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.1.0'

dev_dependencies:
  path: ^1.6.0
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  build_test: ^0.10.0
  test: ^1.3.0
  js: ^0.6.0
