name: dart_devtools
description: DDC debugging tool based on Chrome DevTools
publish_to: none
homepage: https://github.com/dart-lang/devtools-frontend
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.3.0'

dev_dependencies:
  path: ^1.6.0
  build_runner: ^1.0.0
  build_web_compilers: ^1.0.0
  build_test: ^0.10.0
  test: ^1.4.0
  js: ^0.6.0
